# Generated by Django 3.0.4 on 2020-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20200313_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_newsletter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
