# Generated by Django 3.0.3 on 2020-03-05 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200220_1859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0007_auto_20200303_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publisher_company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.PublisherCompany'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
