# Generated by Django 3.0.3 on 2020-03-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200220_1859'),
        ('users_app', '0008_auto_20200305_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publisher_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.PublisherCompany'),
        ),
    ]
