# Generated by Django 3.0.4 on 2020-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_auto_20200305_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'publisher'), (3, 'reader')], default=3),
        ),
    ]
