version: '3'
services:

  db:
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  library_project:
    build: .
    volumes:
      - .:/library_project/
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - django_db.env
    entrypoint: entrypoints/library_project.sh

volumes:
  db_data:
