version: '3'
services:

  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  library_project:
    build:
      context: .
      dockerfile: local/Dockerfile
    volumes:
      - .:/library_project/
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - env/library_project.env
    entrypoint: entrypoints/library_project.sh

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  db_data:
