# Generated by Django 3.0.3 on 2020-02-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50)),
                ("pseudonym", models.CharField(max_length=50)),
                ("birthday", models.DateField()),
                ("deathday", models.DateField(blank=True, null=True)),
                ("country", models.CharField(max_length=50)),
                ("biography", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PublisherCompany",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("cover", models.ImageField(upload_to="")),
                ("year_made", models.PositiveSmallIntegerField()),
                ("page_count", models.PositiveSmallIntegerField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="library_app.Author"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="books", to="library_app.Genre"
                    ),
                ),
                (
                    "publisher_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="library_app.PublisherCompany",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="genres",
            field=models.ManyToManyField(
                related_name="authors", to="library_app.Genre"
            ),
        ),
    ]
