# Generated by Django 3.0.3 on 2020-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("library_app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="publishercompany",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
