# Generated by Django 3.0.3 on 2020-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200220_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthorspriority',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
