# Generated by Django 3.0.3 on 2020-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("library_app", "0003_auto_20200214_1635")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        )
    ]
