# Generated by Django 3.0.3 on 2020-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20200220_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
