# Generated by Django 3.0.3 on 2020-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("library_app", "0004_auto_20200214_1640")]

    operations = [
        migrations.AlterModelOptions(
            name="publishercompany",
            options={"verbose_name_plural": "Publisher companies"},
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
