# Generated by Django 3.0.3 on 2020-02-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("library_app", "0007_auto_20200217_1024")]

    operations = [migrations.RemoveField(model_name="book", name="slug")]
