# Generated by Django 3.0.3 on 2020-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("library_app", "0009_book_slug")]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=150),
        )
    ]
